# file: .golangci.yml
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 10

run:
  timeout: 5m

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should have comment or be unexported"
  include:
    - EXC001
linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
  disable:
    - maligned
    - prealloc
    - scopelint
    - unconvert
