run:
  timeout: 5m
  tests: true


  
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - revive
    - dupl

linters-settings:
  misspell:
    locale: US
  staticcheck:
    checks: ["all"]
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    enable-all-rules: true


issues:
  exclude-files:
    - '.*_test\.go'
  exclude-rules:
    - text: "avoid magic numbers like '0'"
      linters:
        - revive
    - text: "avoid magic numbers like '1'"
      linters:
        - revive


