repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
      - id: go-test-mod
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-sec-mod
      - id: go-fumpt
      - id: go-imports
      - id: go-vet
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.41.1
    hooks:
      - id: golangci-lint
        args: ["--config", ".golangci.yml"]