name: Build

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Build Go project
        run: go build -o myapp
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./app
