name: Codecov

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go: [ 'stable' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Go test with coverage
        run: go test -coverprofile=coverage.out $(go list ./... | grep -v "github.com/lucasvillarinho/nofy/examples")

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}