name: Golang workflow

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  build:
    strategy:
      matrix:
        go: ["stable"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          
      - name: Run Go test
        run: go test -race ./...