name: Golang workflow

on:
  push:
    # paths: ["**.go"]
  pull_request:
    # paths: ["**.go"]

jobs:
  build:
    strategy:
      matrix:
        go: ["stable"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
      
      - name: Unit Test
        run: go test -race ./...