name: Golang workflow

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  build:
    strategy:
      matrix:
        go: ["stable"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...
      
      - name: Run securego/gosec
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
        
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
      
      - name: Run unit test
        run: go test -race ./...