name: Lint

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: app
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
