name: Security 

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  security:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: myapp
      - name: Run govulncheck
        run: ./app && go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...
      - name: Run securego/gosec
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...