name: Unit Test

on:
  push:
    paths: ["**.go"]
  pull_request:
    paths: ["**.go"]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: app
      - name: Run unit tests
        run:  
          go test -race $(go list ./... | grep -v "github.com/lucasvillarinho/nofy/tests/e2e")
